<a href="https://colab.research.google.com/github/sunilmadishetty/AIML-2025/blob/main/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lab 01:Introduction to Python,Numpy,Matplotlib.


In [1]:
import numpy as np
lst1=[1,2,3]
array1 = np.array(lst1)
array1

array([1, 2, 3])

In [2]:
type(lst1)

list

In [3]:

type(array1)

numpy.ndarray

In [4]:

list2=[3,2,1]
array2=np.array(list2)
array2

array([3, 2, 1])

In [5]:
print("array2 multiplied by array1: ",array1*array2)
print("array2 divided by array1: ",array2/array1)
print("array2 raised to the power of array1: ",array2**array1)
print(f" {array2} raised to the power of {array1}:,{array2**array1}")



array2 multiplied by array1:  [3 4 3]
array2 divided by array1:  [3.         1.         0.33333333]
array2 raised to the power of array1:  [3 4 1]
 [3 2 1] raised to the power of [1 2 3]:,[3 4 1]


In [6]:
# sine function
print("Sine: ",np.sin(array1))
# logarithm
print("Natural logarithm: ",np.log(array1))
print("Base-10 logarithm: ",np.log10(array1))
print("Base-2 logarithm: ",np.log2(array1))
# Exponential
print("Exponential: ",np.exp(array1))

Sine:  [0.84147098 0.90929743 0.14112001]
Natural logarithm:  [0.         0.69314718 1.09861229]
Base-10 logarithm:  [0.         0.30103    0.47712125]
Base-2 logarithm:  [0.        1.        1.5849625]
Exponential:  [ 2.71828183  7.3890561  20.08553692]


In [7]:
print("Adding two numpy arrays {array1} and {array2} together:", array1+array2)

Adding two numpy arrays {array1} and {array2} together: [4 4 4]


In [8]:
print(f"Adding two numpy arrays {array1} and {array2} together: {array1+array2}")

Adding two numpy arrays [1 2 3] and [3 2 1] together: [4 4 4]
